'use strict';
const $ = id => document.getElementById(id);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const money = (value, currency) => `${currency} ${Number(value).toLocaleString('en-US', {minimumFractionDigits:2, maximumFractionDigits:2})}`;
const state = {payments:[], selected:null, result:null, stage:'investigation', sequence:0, controller:null, reviewed:false, history:[], storage:true};
const focusIds = ['P50002','P50003','P50001','P50000'];
function notify(message,error=false){$('notification').hidden=!message;$('notification').textContent=message;$('notification').classList.toggle('error',error);}
async function api(path,options={}){const response=await fetch(path,options);let data;try{data=await response.json();}catch{throw new Error('The server returned an unreadable response. Please retry.');}if(!response.ok)throw new Error(data.error||'Request failed.');return data;}
function renderList(){const query=$('search').value.trim().toLowerCase();const rows=state.payments.filter(p=>[p.payment_id,p.client_id,p.beneficiary_name,p.currency].some(v=>v.toLowerCase().includes(query)));rows.sort((a,b)=>{const ia=focusIds.indexOf(a.payment_id),ib=focusIds.indexOf(b.payment_id);return (ia<0?100:ia)-(ib<0?100:ib)||a.payment_id.localeCompare(b.payment_id);});$('count').textContent=rows.length;$('list').replaceChildren();if(!rows.length){$('list').textContent='No matching payments.';return;}let lastGroup='';rows.forEach(p=>{const group=focusIds.includes(p.payment_id)?'Focus cases':'All payment records';if(group!==lastGroup){const label=document.createElement('div');label.className='section-label';label.textContent=group;$('list').append(label);lastGroup=group;}const button=document.createElement('button');button.className='payment';button.type='button';button.setAttribute('aria-pressed',String(p.payment_id===state.selected));button.innerHTML=`<strong>${escapeHTML(p.payment_id)}</strong><span>${escapeHTML(p.beneficiary_name)}</span><span class="amount">${escapeHTML(money(p.amount,p.currency))}</span><span>${escapeHTML(p.client_id)} · ${escapeHTML(p.payment_date)}</span>`;button.onclick=()=>selectPayment(p.payment_id);$('list').append(button);});}
function setStage(stage){if(stage!=='investigation'&&!state.result)return;if(stage==='preview'&&(!state.reviewed||!state.result.external_request_needed))return;state.stage=stage;['investigation','handoff','preview'].forEach(name=>{ $(name).hidden=name!==stage;$('tab-'+name).setAttribute('aria-selected',String(name===stage));});$('heading').textContent=stage==='investigation'?'Payment investigation':stage==='handoff'?(state.result.external_request_needed?'Prepare RM handoff':'Prepare analyst note'):'Customer preview';if(stage==='preview'){$('preview-id').textContent='PAYMENT '+state.selected;$('preview-text').textContent=$('draft').value;}}
function storageKey(){return `payment-clarity:v1:${state.selected}:${state.result.input_version}`;}
function persist(){if(!state.result)return;try{localStorage.setItem(storageKey(),JSON.stringify({text:$('draft').value,reviewedText:state.reviewed?$('draft').value:null,history:state.history}));}catch{state.storage=false;notify('Browser storage is unavailable. Your draft works for this session but will not be saved.');}}
function loadDraft(){let record=null;try{record=JSON.parse(localStorage.getItem(storageKey())||'null');}catch{state.storage=false;}const text=record&&typeof record.text==='string'?record.text:state.result.draft;$('draft').value=text;state.reviewed=Boolean(record&&record.reviewedText===text&&text.trim());state.history=Array.isArray(record?.history)?record.history.filter(x=>x&&typeof x.action==='string'&&typeof x.time==='string').slice(-40):[];updateReview();}
function updateReview(){$('tab-handoff').disabled=!state.result;$('tab-preview').disabled=!state.reviewed||!state.result?.external_request_needed;$('review').disabled=state.reviewed||!$('draft').value.trim();$('review-state').textContent=state.reviewed?'Reviewed locally · Current revision':'Draft · Review required';$('review-history').replaceChildren();if(!state.history.length)$('review-history').textContent='No review events yet.';state.history.slice().reverse().forEach(event=>{const div=document.createElement('div');div.className='review-event';div.textContent=`${event.action} · ${new Date(event.time).toLocaleString()}`;$('review-history').append(div);});}
function evidencePanel(index){const r=state.result;const c=r.checks[index];const evidence=r.evidence.find(e=>e.source===c.source);$('evidence-title').textContent=c.title;$('evidence-source').textContent=c.source;$('evidence-quote').textContent=c.clause;$('evidence-full').textContent=evidence?.text||'Evidence unavailable.';$('evidence-calculation').textContent=c.calculation?`${c.calculation.value} ${c.calculation.value_currency} ${c.calculation.operator} ${c.calculation.threshold} ${c.calculation.threshold_currency} · ${c.calculation.basis}`:'No numerical calculation for this check.';}
function renderResult(){const r=state.result,p=r.payment;const triggered=r.checks.filter(c=>c.triggered);const checks=[...triggered,...r.checks.filter(c=>!c.triggered)];$('result').innerHTML=`<div class="columns"><div><article class="panel decision"><span class="eyebrow">REQUIRED REVIEW</span><h2>${escapeHTML(r.title)}</h2><div class="chip-row">${r.requirements.map(t=>`<span class="chip">${escapeHTML(t)}</span>`).join('')}<span class="chip">${r.status==='incomplete'?'Evidence incomplete':'Ready for human review'}</span></div>${checks.map(c=>`<div class="rule ${c.state==='complete'?'':'unresolved'}"><div class="rule-title"><span class="check-symbol">${c.state!=='complete'?'!':c.triggered?'●':'✓'}</span>${escapeHTML(c.title)}${c.triggered?' · Review required':''}</div><p>${escapeHTML(c.detail)}</p><button class="source-button" data-evidence="${r.checks.indexOf(c)}">View policy evidence</button></div>`).join('')}</article>
<article class="panel"><h3>Payment facts</h3><dl class="facts"><div><dt>Amount</dt><dd class="big">${escapeHTML(money(p.amount,p.currency))}</dd></div><div><dt>Client / region</dt><dd>${escapeHTML(p.client_id)} / ${escapeHTML(r.client.country)}</dd></div><div><dt>Beneficiary</dt><dd>${escapeHTML(p.beneficiary_name)}</dd></div><div><dt>Authoritative destination code</dt><dd>${escapeHTML(p.beneficiary_country_code)}</dd></div><div><dt>Recorded date / channel</dt><dd>${escapeHTML(p.payment_date)} / ${escapeHTML(p.channel)}</dd></div><div><dt>Client risk rating in source</dt><dd>${escapeHTML(r.client.risk_rating)}</dd></div></dl>${r.discrepancy?`<div class="warning">${escapeHTML(r.discrepancy.message)}</div>`:''}</article>
<article class="panel"><h3>Related payments · ${escapeHTML(r.related_group.date)}</h3><p class="micro">Same client, beneficiary, calendar date, and native currency. ${r.history_count} payment records inspected for this client.</p><div class="table-wrap"><table><thead><tr><th>Payment</th><th>Channel</th><th class="num">Amount</th></tr></thead><tbody>${r.related_group.payments.map(x=>`<tr><td>${escapeHTML(x.payment_id)}</td><td>${escapeHTML(x.channel)}</td><td class="num">${escapeHTML(money(x.amount,x.currency))}</td></tr>`).join('')}<tr><td colspan="2"><strong>Combined total</strong></td><td class="num"><strong>${escapeHTML(money(r.related_group.total_amount,p.currency))}</strong></td></tr></tbody></table></div></article>
<article class="panel"><details><summary>Assumptions and unresolved information</summary><ul>${[...r.assumptions,...r.missing_information].map(t=>`<li>${escapeHTML(t)}</li>`).join('')}</ul><p>A trigger does not establish wrongdoing. No payment action is authorised.</p></details></article>${r.ai_explanation?`<article class="panel"><span class="eyebrow">AI EXPLANATION · REVIEW REQUIRED</span><p>${escapeHTML(r.ai_explanation)}</p></article>`:''}<div class="next-row"><div><strong>${r.external_request_needed?'Next: prepare a precise RM request':'Next: record the analyst review'}</strong><p>Keep the evidence with the next action.</p></div><button id="prepare" class="button primary">${r.external_request_needed?'Prepare RM request':'Prepare analyst note'} →</button></div></div>
<aside><section class="panel"><span class="eyebrow">POLICY EVIDENCE</span><h3 id="evidence-title"></h3><p class="source-name" id="evidence-source"></p><blockquote class="quote" id="evidence-quote"></blockquote><p class="micro" id="evidence-calculation"></p><details><summary>Read full source</summary><p id="evidence-full" class="quote"></p></details><hr><p class="micro">Supplied exercise policy<br>Snapshot ${escapeHTML(r.input_version)}</p></section><section class="panel"><h3>${r.external_request_needed?'Information to request':'Analyst next steps'}</h3><ul class="plain-list">${(r.request_items.length?r.request_items:['Inspect all completed checks','Resolve data discrepancies','Follow the bank review procedure']).map(t=>`<li>${escapeHTML(t)}</li>`).join('')}</ul><p class="micro">Proposed checklist. Confirm necessity before contacting a customer.</p></section><details class="panel"><summary>Actual tool activity (${r.trace.length})</summary>${r.trace.map(t=>`<div class="trace"><code>${escapeHTML(t.tool)}</code><pre>${escapeHTML(JSON.stringify(t.arguments,null,2))}</pre>${t.initiated_by?'LLM requested':''}</div>`).join('')}</details><section class="panel"><h3>Execution mode</h3><p class="small">${escapeHTML(r.mode_label)}</p><p class="micro">${escapeHTML(r.limitation)}</p><p class="micro">Generated ${escapeHTML(new Date(r.generated_at).toLocaleTimeString())}</p></section></aside></div>`;
$('result').querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>evidencePanel(Number(b.dataset.evidence)));$('prepare').onclick=()=>setStage('handoff');evidencePanel(r.checks.indexOf(triggered[0]||r.checks[0]));$('draft-type').textContent=r.external_request_needed?'RM HANDOFF':'INTERNAL ANALYST NOTE';$('draft-title').textContent=r.external_request_needed?'A precise request, ready to review.':'Record the next review step.';$('draft-description').textContent=r.external_request_needed?'Check the wording and requested information before creating a client preview.':'No customer request was established by these checks. Keep this note internal.';loadDraft();$('export').disabled=false;}
async function selectPayment(id){state.selected=id;renderList();await runInvestigation();}
async function runInvestigation(){if(!state.selected)return;const current=++state.sequence;state.controller?.abort();state.controller=new AbortController();state.result=null;state.reviewed=false;setStage('investigation');$('result').hidden=true;$('loading').hidden=false;$('loading').innerHTML='<span class="spinner"></span><h2>Checking facts and policies</h2><p class="muted">Gathering evidence and related payments.</p>';$('tab-handoff').disabled=true;$('tab-preview').disabled=true;$('export').disabled=true;$('investigate').disabled=true;notify('');$('crumb').textContent=state.selected;const p=state.payments.find(x=>x.payment_id===state.selected);$('subtitle').textContent=p?`${p.payment_id} · ${p.beneficiary_name} · ${p.payment_date}`:state.selected;const timer=setTimeout(()=>state.controller?.abort(),40000);try{const result=await api('/api/investigate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payment_id:state.selected,question:$('question').value.trim()}),signal:state.controller.signal});if(current!==state.sequence)return;state.result=result;renderResult();$('result').hidden=false;$('mode').textContent=result.mode_label;if(result.mode==='fallback')notify(result.limitation);if(result.status==='incomplete')notify('Some checks need more evidence. Review the unresolved information before proceeding.');}catch(error){if(current!==state.sequence)return;notify(error.name==='AbortError'?'The investigation timed out. You can retry.':error.message,true);}finally{clearTimeout(timer);if(current===state.sequence){$('loading').hidden=true;$('investigate').disabled=false;}}}
$('search').addEventListener('input',renderList);$('question-form').addEventListener('submit',e=>{e.preventDefault();runInvestigation();});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setStage(b.dataset.tab));$('back-evidence').onclick=()=>setStage('investigation');$('draft').oninput=()=>{if(state.reviewed)state.history.push({action:'Edited; previous review invalidated',time:new Date().toISOString()});state.reviewed=false;updateReview();persist();};$('review').onclick=()=>{if(!$('draft').value.trim())return;state.reviewed=true;state.history.push({action:'Current draft reviewed locally',time:new Date().toISOString()});updateReview();persist();};$('export').onclick=()=>{if(!state.result)return;const data={...state.result,local_draft:{text:$('draft').value,reviewed:state.reviewed,history:state.history},notice:'Synthetic local demo. Not a payment approval.'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`payment-clarity-${state.selected}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function init(){try{const [health,records]=await Promise.all([api('/api/health'),api('/api/payments')]);state.payments=records.payments;$('mode').textContent=health.live_ai_configured?'Live AI configured':'Evidence mode · no live AI';$('version').textContent=`Source snapshot ${health.version.slice(0,8)}`;$('investigate').disabled=false;await selectPayment('P50002');}catch(error){$('loading').hidden=true;notify('Unable to load the workspace. '+error.message,true);$('list').textContent='Source records unavailable. Reload after restarting the server.';}}
init();
// Optional structured controls use the same actions and state as the visible app.
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  const tools=[
    {name:'read_payment_workspace',description:'Read the selected synthetic payment, investigation state, local draft review state, and current screen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(){return {payment_id:state.selected,screen:state.stage,status:state.result?.status||'loading',title:state.result?.title||null,requirements:state.result?.requirements||[],related_total:state.result?.related_group.total_amount||null,reviewed:state.reviewed,mode:state.result?.mode||null,draft:$('draft').value};}},
    {name:'investigate_payment',description:'Select and investigate one supplied synthetic payment, updating the visible workspace. No payment action or external message occurs.',inputSchema:{type:'object',properties:{payment_id:{type:'string'}},required:['payment_id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){if(!input||typeof input.payment_id!=='string'||!state.payments.some(p=>p.payment_id===input.payment_id))throw new Error('Unknown supplied payment');await selectPayment(input.payment_id);if(!state.result||state.selected!==input.payment_id)throw new Error('Investigation did not complete');return {payment_id:state.selected,title:state.result.title,requirements:state.result.requirements,related_total:state.result.related_group.total_amount,mode:state.result.mode};}},
    {name:'stage_rm_request',description:'Edit the current local draft and open the handoff screen. This invalidates previous review; it does not send or approve anything.',inputSchema:{type:'object',properties:{payment_id:{type:'string'},text:{type:'string',minLength:1,maxLength:10000}},required:['payment_id','text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!state.result||!input||input.payment_id!==state.selected||typeof input.text!=='string'||!input.text.trim()||input.text.length>10000)throw new Error('A current payment and a non-empty draft are required');$('draft').value=input.text;$('draft').dispatchEvent(new Event('input'));setStage('handoff');return {payment_id:state.selected,screen:state.stage,reviewed:state.reviewed};}}
  ];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability; app remains fully usable. */}}
}
